name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Create Android Structure
        run: flutter create --platforms android --project-name nexus_app .

      # این مرحله جدید است: آپدیت خودکار نسخه کاتلین برای رفع ارور وب‌ویو
      - name: Fix Kotlin Version
        run: |
          sed -i 's/1.7.1/1.9.24/g' android/settings.gradle
          sed -i 's/1.8.22/1.9.24/g' android/settings.gradle

      - name: Install Packages
        run: flutter pub get

      - name: Generate App Icon
        run: flutter pub run flutter_launcher_icons

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nexus-App-Release
          path: build/app/outputs/flutter-apk/app-release.apk
